### ISSUE TITLE
Specify master directly when connecting to replica

### ISSUE THREAD

**Issue by dataindataout** [github/gh-ost#212]
I see when using the "connect to replica, migrate on master" method, the master is detected via the function here https://github.com/github/gh-ost/blob/f06b469227208000d70739233fc222b1b4998f04/go/mysql/utils.go#L77.

Is there a way (that I've missed) to specify the master directly via a flag? If not, would making this configurable cause any architecture issues or predictable bugs?

Thank you!

**Comment by shlomi-noach** [comment]
@dataindataout there is no way to do that right now. Adding this would not cause a significant architectural change. 

Can you elaborate on the need?

The risk I see is someone wrongly specifying a master which is not on same topology (though `gh-ost` can presumably check it out)

**Comment by shlomi-noach** [comment]
Or, another more likely risk is the user specifying a non-master server.

**Comment by dataindataout** [comment]
Thank you for the reply! The use case would be non-native replication (e.g., Tungsten replicator), so a show slave status doesn't provide information. By the way, this is working functionally with the "Connect to master" method, of course.

**Comment by shlomi-noach** [comment]
ahh... didn't cross my mind. Then, yes, it's possible. I might do this in the next week or two.

**Comment by dataindataout** [comment]
Thank you for taking a look at it!

**Comment by shlomi-noach** [comment]
@dataindataout out of curiosity, is your topology that uses tungsten strictly RBR?

**Comment by dataindataout** [comment]
It's actually SBR (and can't be changed), so we've found that we do need to run it from a replica.

**Comment by shlomi-noach** [comment]
@dataindataout I don't have a tungsten setup on me, could you please answer the following: if I were to look at one of your replica servers, replicating via tungsten, is there any indication at all in that server that it acts as a replica? I assume `show slave status` shows empty result. What would be a way for `gh-ost` (or any client) to say "oh yeah, this is a tungsten-based replica" ?

**Comment by dataindataout** [comment]
Yes, show slave status is blank:
mysql> show slave status\G
Empty set (0.00 sec)

From mysql, you can see the tungsten connections, but of course there's no guarantee someone has named their user "tungsten":

mysql> show processlist\G
*************************** 1. row ***************************
           Id: 48
         User: tungsten
         Host: tungstenslave:52707
           db: tungsten_cookbook
      Command: Sleep
         Time: 2654
        State:
         Info: NULL
    Rows_sent: 0
Rows_examined: 0
    Rows_read: 0

There's nothing else we can think of or find within mysql to definitively indicated the slave is using tungsten.

If you hop out to the system level, you can see the tungsten java process running (ps aux | grep tungsten). 

There are also tungsten tools at the system level like trepctl status. From a slave:

trepctl status | egrep 'role|pipeline'
pipelineSource         : thl://tungstenmaster:2112/
role                   : slave

Will any of these work?

**Comment by shlomi-noach** [comment]
Thank you -- none of these would work from the MySQL connection's point of view. This is still OK; the command-line flag would need to be named something like `--yes-i-know-i-know-this-is-tungsten-trust-me`

**Comment by dataindataout** [comment]
:)

**Comment by pmkane** [comment]
We have an active/passive replication setup, without tungsten (master-master, but only a single writer) and would also like to be able to specify or suggest which host is the master.  Currently, gh-ost picks the wrong host.

**Comment by Roguelazer** [comment]
Being able to manually specify the master would also fix the master/master issues that I brought up in #144... :-)

**Comment by twotwotwo** [comment]
I implemented an `-override-applier-host` option, only allowed when you also pass `-allow-master-master`, and @pmkane tried it out successfully. I'll drop the code into a PR referencing this issue, though of course I get it if for design or other reasons it isn't what you want.

**Comment by shlomi-noach** [comment]
@twotwotwo thank you for working on this!

Your solution will work for master-master setup, but does not quite solve the `tungsten` setup, because `gh-ost` will look at the replica and say "hey, this _isn't a replica_". We will need to override that as well.

I'll look into it some more.

**Comment by twotwotwo** [comment]
Ah, got it, now I understand the thread better. Makes sense!

**Comment by shlomi-noach** [comment]
@twotwotwo or -- not! Actually this produces the desired behavior. I'm going to merge the PR and change a couple things:

- going to rename flag to `--assume-master-host`
- will allow it to run even without `master-master`, so as to support `tungsten`. Though I still want to have _some_ constraint. Looking further into.

**Comment by shlomi-noach** [comment]
@dataindataout as per https://github.com/github/gh-ost/pull/223, you will execute:

```
gh-ost --tungsten --assume-master-host=the.master.com
```

**Comment by shlomi-noach** [comment]
This will likely be merged an released early next week.

**Comment by dataindataout** [comment]
Wow, thank you! I look forward to giving it a try.

**Comment by shlomi-noach** [comment]
closed by #223

**Comment by shlomi-noach** [comment]
Released in https://github.com/github/gh-ost/releases/tag/v1.0.17

**Comment by dataindataout** [comment]
Thanks! I have been OOTO and will test this this week.

**Comment by dataindataout** [comment]
Hi, I've tested this. I tried this on .20 but then reverted to .17 to avoid any conflicts after an initial error. I also tried eliminating a few of the flags to see if something was conflicting. 

Here is my last test and result:

(.145 is the master, .144 is the slave; using Tungsten replicator.)

`[root@tungstenslave ~]# ./gh-ost \
> --assume-master-host=192.168.56.145 \
> --tungsten \
> --max-load=Threads_running=25 \
> --critical-load=Threads_running=1000 \
> --chunk-size=1000 \
> --throttle-control-replicas="192.168.56.144" \
> --max-lag-millis=1500 \
> --user="ghost" \
> --password="ghost" \
> --host=192.168.56.144 \
> --database="mysqlslap" \
> --table="t1" \
> --verbose \
> --alter="add column whatever varchar(50)" \
> --switch-to-rbr \
> --cut-over=default \
> --default-retries=120 \
> --panic-flag-file=/tmp/ghost.panic.flag \
> --postpone-cut-over-flag-file=/tmp/ghost.postpone.flag \
> --initially-drop-ghost-table
2016-09-01 13:10:04 INFO starting gh-ost 1.0.17
2016-09-01 13:10:04 INFO Migrating `mysqlslap`.`t1`
2016-09-01 13:10:04 INFO connection validated on 192.168.56.144:3306
2016-09-01 13:10:04 INFO User has SUPER, REPLICATION SLAVE privileges, and has ALL privileges on `mysqlslap`.*
2016-09-01 13:10:04 INFO binary logs validated on 192.168.56.144:3306
2016-09-01 13:10:04 INFO Restarting replication on 192.168.56.144:3306 to make sure binlog settings apply to replication thread
2016-09-01 13:10:04 INFO Table found. Engine=InnoDB
2016-09-01 13:10:04 INFO Estimated number of rows via EXPLAIN: 9407
2016-09-01 13:10:04 FATAL It seems like this migration attempt to run directly on master. Preferably it would be executed on a replica (and this reduces load from the master). To proceed please provide --allow-on-master`

It appears that the correct context is not getting picked up from the --assume-master-host flag, and that InspectorIsAlsoApplier is remaining true.

I may not have the complete list of required flags; can you please take a look and let me know if you see anything out of place? Can you also let me know how I can set up to send you proper testing output, if the above is not sufficient? 

Ongoing thanks to you!

**Comment by shlomi-noach** [comment]
@dataindataout as per the error message: `To proceed please provide --allow-on-master`

**Comment by shlomi-noach** [comment]
`gh-ost` is very demanding in command line flags. I'll review this approach in the future, but right now the theme is to put protection walls around everything.

**Comment by dataindataout** [comment]
Ah, in my testing, I had come to consider --allow-on-master to mean "I acknowledge I am the master, run this change on me." So for Tungsten replication, to run from the replica, I need these three flags: 
```
--assume-master-host=the-master-IP 
--tungsten 
--allow-on-master 
```

That works functionally & will proceed with load testing.

Thank you again!

**Comment by groenewold-pythian** [comment]
Hi, first of all thank you for this feature. Would it be possible to run using --tungsten and without --allow-on-master so that the slaves binlogs are scanned instead? That would require Tungsten to be installed with --log-slave-updates to write events to the slaves binlogs (note this is similar to mysql option --log-slave-updates)

**Comment by shlomi-noach** [comment]
Hi @groenewold-pythian, thank you for the questions and feedback. Since you're commenting on an Issue that was closed, it's going to be difficult to keep track on progress. Could you possibly open a new issue -- actually there's two issues in your comment, and potentially refer back to this issue for reference?

**Comment by groenewold-pythian** [comment]
Will do. Thanks!

**Comment by shlomi-noach** [comment]
@dataindataout 

> Ah, in my testing, I had come to consider --allow-on-master to mean "I acknowledge I am the master, run this change on me." So for Tungsten replication

Actually, you are right; `gh-ost` should not have asked you to `allow-on-master`; this will be fixed.

**Comment by dataindataout** [comment]
Hey, thanks! It will be great to allow this to connect to the replica.

**Comment by shlomi-noach** [comment]
@dataindataout https://github.com/github/gh-ost/pull/263 removes the need for `allow-on-master`

**Comment by dataindataout** [comment]
Thanks, @shlomi-noach ! I'll take it for a spin.
